// <auto-generated />
using System;
using MetricService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetricService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117163535_AddFileNameToMetricValue")]
    partial class AddFileNameToMetricValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricService.Domain.Entities.FileResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageExecutionTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("AverageValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("DeltaTimeSeconds")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("MaxValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique()
                        .HasDatabaseName("IX_Results_FileName");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("MetricService.Domain.Entities.MetricValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ExecutionTime")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<double>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("Values", (string)null);
                });

            modelBuilder.Entity("MetricService.Domain.Entities.MetricValue", b =>
                {
                    b.HasOne("MetricService.Domain.Entities.FileResult", "Result")
                        .WithMany("MetricValues")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("MetricService.Domain.Entities.FileResult", b =>
                {
                    b.Navigation("MetricValues");
                });
#pragma warning restore 612, 618
        }
    }
}
